### ISSUE TITLE
Unable to install - Invalid index definition

### ISSUE THREAD

**Issue by mudrd8mz** [center-for-learning-management/moodle-auth_shibboleth_link#1]
I get this when trying to install the plugin under PostgreSQL:

Coding error detected, it must be fixed by a programmer: Invalid index definition in table {auth_shibboleth_link}: the composed index on fields "idp,idpusername" is too long. Limit is 999 bytes / 333 chars.

```
    line 423 of /lib/ddl/sql_generator.php: coding_exception thrown
    line 131 of /lib/ddl/postgres_sql_generator.php: call to sql_generator->getCreateIndexSQL()
    line 358 of /lib/ddl/sql_generator.php: call to postgres_sql_generator->getCreateIndexSQL()
    line 250 of /lib/ddl/sql_generator.php: call to sql_generator->getCreateTableSQL()
    line 415 of /lib/ddl/database_manager.php: call to sql_generator->getCreateStructureSQL()
    line 370 of /lib/ddl/database_manager.php: call to database_manager->install_from_xmldb_structure()
    line 614 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
    line 1877 of /lib/upgradelib.php: call to upgrade_plugins()
    line 694 of /admin/index.php: call to upgrade_noncore()
```

**Comment by rschrenk** [comment]
Dear David,
thank you for your feedback. I checked the install.xml with the XMLDBEditor directly in out Moodle, but it did not complain about that index. Perhaps there could be a prior check according to this.
As the index is not really necessary, I just dropped it in commit fe8ca0c4b69f01c6b9f8d5dff7600e2a4c786fe2.
Kind regards

**Comment by mudrd8mz** [comment]
> Perhaps there could be a prior check according to this

Yes, this was new for me as well. I raised the topic with Eloy Lafuente (the Moodle HQ database expert) in the general moodle dev chat and it was confirmed that the XMLDB is lacking this pre-check, and we only check it on the actual DDL execution. Please feel encouraged to report it as a new XMLDB bug into the Moodle tracker!

Thank you for the prompt fix.

**Comment by rschrenk** [comment]
Great, I will do so.
I tested the plugin once with the moved lib.php and without the index. It seemed to work.
Shall I update the plugin in the moodle plugins-DB, or do you proceed with your review using GitHub, and I publish after the review, if nothing else has to be done?
Greetz

**Comment by mudrd8mz** [comment]
Yes please, release a new version in the plugins directory. We only review packages available there, not in the Github. Thank you.

**Comment by rschrenk** [comment]
Ok, did so!
