### ISSUE TITLE
Login.php receiving wantsurl

### ISSUE THREAD

**Issue by rschrenk** [center-for-learning-management/moodle-auth_shibboleth_link#10]
Derzeit kann eine Shibboleth-Authentifizierung nicht direkt mit einer Wantsurl getriggert werden, weil `auth/shibboleth_link/login.php` keinen solchen Parameter entgegennimmt. Das läuft derzeit nur über `login/index.php` indirekt. Dort hat der User aber die Wahl, welche Loginmethode zu verwenden ist. Wir benötigen für die eduthek.neu die MÖglichkeit, dass direkt der Bildungsportal-SSO verwendet wird.

**Comment by rschrenk** [comment]
Hallo @lassnj 
ich habe diese Änderung eingebracht, die wir für die eduthek.neu benötigen. Damit ist gewährleistet, dass ein Login direkt über den SSO getriggert werden kann und die Nutzer/innen nach dem Login zum gewünschten Kurs weitergeleitet werden.
Bitte beim Update im August berücksichtigen!
LG

**Comment by lassnj** [comment]
@prowebat bitte beim Sommerupdate berücksichtigen

**Comment by prowebat** [comment]
habe einen check ergänzt, dass die wantsurl immer einen moodle local url (gleiche domain) sein muss.
