### ISSUE TITLE
Move auth_shibboleth_link\lib to autoloadable classes

### ISSUE THREAD

**Issue by mudrd8mz** [center-for-learning-management/moodle-auth_shibboleth_link#2]
I would expect this is an autoloadabla class defined in a file under the "classes" directory. Any reason why it is not there?

**Comment by rschrenk** [comment]
I placed the lib.php in classes directory in commit 6babdfeb493a1e613dd2ab97ed436afd6f88c413.
Kind regards

**Comment by mudrd8mz** [comment]
Thanks. Just to note, there should be no need to load the classes from there manually. They are autoloaded by the core (given the name is correct).

https://docs.moodle.org/dev/Automatic_class_loading
