### ISSUE TITLE
Upgrade warning

### ISSUE THREAD

**Issue by dasistwas** [center-for-learning-management/moodle-auth_shibboleth_link#5]
Upgrade warnings.

Invalid get_string() identifier: 'settings:hooks' or component 'auth_shibboleth_link'. Perhaps you are missing $string['settings:hooks'] = ''; in /usr/www/users/lernst/eduvidual_wunderbyte_at/auth/shibboleth_link/lang/en/auth_shibboleth_link.php?

    line 353 of /lib/classes/string_manager_standard.php: call to debugging()
    line 7391 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
    line 55 of /auth/shibboleth_link/settings.php: call to get_string()
    line 85 of /lib/classes/plugininfo/auth.php: call to include()
    line 134 of /admin/settings/plugins.php: call to core\plugininfo\auth->load_settings()
    line 8672 of /lib/adminlib.php: call to require()
    line 22 of /admin/upgradesettings.php: call to admin_get_root()

Invalid get_string() identifier: 'settings:hooks:description' or component 'auth_shibboleth_link'. Perhaps you are missing $string['settings:hooks:description'] = ''; in /usr/www/users/lernst/eduvidual_wunderbyte_at/auth/shibboleth_link/lang/en/auth_shibboleth_link.php?

    line 353 of /lib/classes/string_manager_standard.php: call to debugging()
    line 7391 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
    line 56 of /auth/shibboleth_link/settings.php: call to get_string()
    line 85 of /lib/classes/plugininfo/auth.php: call to include()
    line 134 of /admin/settings/plugins.php: call to core\plugininfo\auth->load_settings()
    line 8672 of /lib/adminlib.php: call to require()
    line 22 of /admin/upgradesettings.php: call to admin_get_root()

Skip to main content
Expert mode
All functions of this page are displayed in expert mode!

**Comment by rschrenk** [comment]
This string is there.... please check if you use an outdated version.
